### ISSUE TITLE
xsser not working

### ISSUE THREAD

**Issue by Huss-wq** [Tanvir0075/xsser#1]
When I install the xsser in my kali linux 2020.4 and run it 
this message appeared to me: 
[Error] Cannot import lib:PyCurl 

and when I install the PyCurl in kali linux and run xsser again this message appeared again how to solve this problem. I need some help please.

**Comment by mr-vill4in** [comment]
it's your python package problem 
I've tested xsser , it's working fine 
you can fix your problem [click here to open](https://stackoverflow.com/questions/7391638/pycurl-installed-but-not-found)
![xsser](https://user-images.githubusercontent.com/51061936/112225271-b794f200-8c56-11eb-811b-84f366a0c4bd.png)
